### ISSUE TITLE
example usage

### ISSUE THREAD

**Issue by Dobiasd** [sleepokay/average_faces#1]
The result of your work looks really good. I would like to test it out on a bunch of portrait images. Could you provide an example on how to use your code?

**Comment by sleepokay** [comment]
Hey! So sorry to get back to you late. The past month has been a complexity. I'll have a look at my old files and see if I can put up some documentation for you.

**Comment by Dobiasd** [comment]
Thanks a lot, but don't worry. I figured out how to use your code by reading it. ;)
It worked out fine, and I'm long done with my experiments.
